### PR TITLE
assignment 2 submit

### PR DESCRIPTION
**Pull request by hameed980**
assignment 2 submit

### CODE REVIEW

**Comment by aiwithqasim** [comment]
Why delete Assignment 1 and changed files in assignment folder ?

**Comment by aiwithqasim** [comment]
You should add inly assignment 2 files rest things should be unchanged

**Comment by hameed980** [comment]
by mistakenly deleted. now how to solve this problem

**Comment by aiwithqasim** [comment]
download the original assignment file and kept them there in the folder without changing them

**Pull request closed without merging**
