### PR TITLE
MUHAMMAD-SAMEER-339586

### PR DESCRIPTION
**Pull request by icsameer**

### CODE REVIEW

**Comment by icsameer** [comment]
assigment 01

**Comment by aiwithqasim** [comment]
Please create a folder by your name and roll number [sample](https://github.com/aiwithqasim/cde-b1-assignments/pull/2/files#diff-6c1002b8fe7e00c666f4e0769d63f09daacdf02ec84cf36217383d0bb5932489R1) and add your assignment file in it

**Comment by aiwithqasim** [comment]
https://github.com/aiwithqasim/cde-b1-assignments/pull/93 ( Ok to close this one.)

**Comment by icsameer** [comment]
im

**Pull request closed without merging**
