### PR TITLE
1st assignment FAISAL_339240

### PR DESCRIPTION
**Pull request by Faxsal**
1st assignment

### CODE REVIEW

**Comment by aiwithqasim** [comment]
Add assignment file in my assignment folder

**Comment by Faxsal** [comment]
aiwithqasim/cde-b1-assignments

Dear [sir]   I hope this message finds you well. The assignment file has
been added, and the Git demo again file has been merge. Please let me know
if you have any questions., Best regards

**Comment by aiwithqasim** [comment]
Please rename the folder naem to your your name_ rollnumber I:e., QASIMHASSAN_123456

image

**Comment by Faxsal** [comment]
done sir

**Comment by aiwithqasim** [comment]
Perfect.

**Comment by aiwithqasim** [comment]
Implement the MR.

**Pull request merged**
